

- hosts: node
  name: kata
  gather_facts: False
  become: false
  tasks:
    - name: remove the kvm module
      modprobe:
        name: kvm-intel
        state: absent
    - name: enable nested virt
      copy:
        dest: "/etc/modprobe.d/kvm.conf"
        content: |
          options kvm-intel nested=y
    - name: add the kvm module
      modprobe:
        name: kvm-intel
        state: present

    - name: add kata repo signing key
      apt_key:
        url: http://download.opensuse.org/repositories/home:/katacontainers:/releases:/x86_64:/stable-1.4/xUbuntu_18.04/Release.key
        state: present
    - name: add kata repo
      apt_repository:
        repo: deb http://download.opensuse.org/repositories/home:/katacontainers:/releases:/x86_64:/stable-1.4/xUbuntu_18.04/ /
        state: present
        filename: kata-containers

    - name: kata packages
      apt:
        name: kata-runtime,kata-proxy,kata-shim

    - name: kata-deploy
      shell: |
        kata-runtime kata-check
      args:
        executable: /bin/bash
